create sequence project_id_seq;

alter sequence project_id_seq owner to "event-app-manager";

create sequence events_id_seq
    as integer;

alter sequence events_id_seq owner to "event-app-manager";

create sequence events_id_seq1;

alter sequence events_id_seq1 owner to "event-app-manager";

create sequence events_id_seq2;

alter sequence events_id_seq2 owner to "event-app-manager";

create sequence projects_id_seq;

alter sequence projects_id_seq owner to "event-app-manager";

create sequence events_id_seq3;

alter sequence events_id_seq3 owner to "event-app-manager";

create sequence events_shedule_id_seq
    as integer;

alter sequence events_shedule_id_seq owner to "event-app-manager";

create table pwd_reset
(
    id           serial
        primary key,
    email        text not null,
    selector     text not null,
    token        text not null,
    expires_time text not null
);

alter table pwd_reset
    owner to "event-app-manager";

create table users_details
(
    id              serial
        constraint user_details_id_key
            unique,
    name            varchar(100)        not null,
    surname         varchar(100)        not null,
    phone           varchar(20)         not null,
    status          integer   default 1 not null,
    active          integer   default 0,
    activation_code varchar(255)        not null,
    activated_at    date,
    created_at      timestamp default CURRENT_TIMESTAMP,
    updated_at      date      default CURRENT_TIMESTAMP,
    last_login      timestamp,
    ip_address      varchar(255)
);

comment on column users_details.status is '1 = normal, 2 = moderator, 3 = administrator';

alter table users_details
    owner to "event-app-manager";

create table users
(
    id              integer generated by default as identity
        constraint users_pk
            primary key,
    email           varchar(255) not null,
    password        varchar(255) not null,
    id_user_details integer default 0
        constraint users_user_details_id_fk
            references users_details (id)
            on update cascade on delete cascade
);

alter table users
    owner to "event-app-manager";

create table depot_items
(
    id             integer generated always as identity
        constraint project_pk
            primary key,
    name           varchar(100) not null,
    description    text,
    created_at     timestamp    not null,
    id_assigned_by integer      not null
        constraint projects_users_null_fk
            references users
            on update cascade on delete cascade,
    image          varchar(255),
    barcode        varchar(255)
);

alter table depot_items
    owner to "event-app-manager";

alter sequence projects_id_seq owned by depot_items.id;

create table events
(
    id             integer generated by default as identity
        constraint events_pk
            primary key,
    title          varchar(255) not null,
    description    varchar,
    status         varchar(255),
    type           varchar(255),
    created_at     date         not null,
    event_start    timestamp    not null,
    id_assigned_by integer      not null,
    event_end      timestamp,
    location       varchar(255)
);

alter table events
    owner to "event-app-manager";

alter sequence events_id_seq1 owned by events.id;

alter sequence events_id_seq2 owned by events.id;

alter sequence events_id_seq3 owned by events.id;

create table user_event_roles
(
    id        serial
        primary key
        unique,
    role_name varchar(255)
);

alter table user_event_roles
    owner to "event-app-manager";

create table user_event
(
    id_users  integer not null
        constraint user_event_users_null_fk
            references users
            on update cascade on delete cascade,
    id_events integer not null
        constraint user_event_events_null_fk
            references events
            on update cascade on delete cascade,
    id_roles  integer
        constraint user_event_user_event_roles_null_fk
            references user_event_roles
            on update cascade on delete cascade
);

alter table user_event
    owner to "event-app-manager";

create table events_logs
(
    id          serial
        primary key,
    id_users    integer      not null
        constraint events_logs_users_null_fk
            references users
            on update cascade on delete cascade,
    log_content varchar(255) not null,
    date        timestamp
);

alter table events_logs
    owner to "event-app-manager";

create table depot_quantity
(
    id       serial
        primary key,
    id_items integer
        constraint depot_quantity_depot_items_null_fk
            references depot_items,
    quantity integer
);

comment on table depot_quantity is 'ilość magazynowa';

comment on column depot_quantity.quantity is 'ilość magazynowa';

alter table depot_quantity
    owner to "event-app-manager";

create table rental
(
    id          serial
        primary key,
    events_id   integer
        constraint rental_events_null_fk
            references events
            on update cascade on delete cascade,
    users_id    integer
        constraint rental_users_null_fk
            references users,
    items_id    integer not null
        constraint rental_depot_items_null_fk
            references depot_items
            on update cascade on delete cascade,
    quantity    integer not null,
    start_date  date,
    return_date date,
    comments    varchar(255)
);

alter table rental
    owner to "event-app-manager";

create table events_schedules
(
    id          integer default nextval('events_shedule_id_seq'::regclass) not null,
    id_events   integer                                                    not null
        constraint events_shedule_events_null_fk
            references events
            on update cascade on delete cascade,
    title       text                                                       not null,
    description text,
    start_date  timestamp,
    end_date    timestamp
);

alter table events_schedules
    owner to "event-app-manager";

alter sequence events_shedule_id_seq owned by events_schedules.id;

create table meetings
(
    id       serial
        primary key,
    topic    text,
    date     timestamp,
    tasks    text,
    location text
);

alter table meetings
    owner to "event-app-manager";

create table user_meetings
(
    id          serial
        primary key,
    id_meetings integer
        constraint user_meetings_meetings_null_fk
            references meetings
            on update cascade on delete cascade,
    id_users    integer
        constraint user_meetings_users_null_fk
            references users
            on update cascade on delete cascade
);

alter table user_meetings
    owner to "event-app-manager";

