version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/EventAppManager/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/EventAppManager/

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: event-app-manager
      POSTGRES_PASSWORD: postgres_pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - default

volumes:
  postgres: